#ifndef _BT_REG_H_
#define _BT_REG_H_
#define	mem_le_adv_transmit                     	0x0000
#define	mem_le_adv_waitcnt                      	0x0001
#define	mem_sbc_error                           	0x0002
#define	mem_le_adv_rcv                          	0x0002
#define	mem_le_req_rcv                          	0x0003
#define	mem_le_scanrsp_rcv                      	0x0004
#define	mem_le_conn_rcv                         	0x0005
#define	mem_inquiryscan_waitcnt                 	0x0006
#define	mem_inquiryscan_rcvcnt                  	0x0007
#define	mem_pagescan_waitcnt                    	0x0008
#define	mem_pagescan_rcvcnt                     	0x0009
#define	mem_pagescan_rcvfhscnt                  	0x000a
#define	mem_slave_rcvcnt                        	0x000b
#define	mem_page_transmit                       	0x000c
#define	mem_page_rcv                            	0x000d
#define	mem_page_rcv_fhs                        	0x000e
#define	mem_master_rcvcnt                       	0x000f
#define	mem_fhs_wait_counter                    	0x0010
#define	mem_newconnto_counter                   	0x0011
#define	mem_inquiry_transmit                    	0x0012
#define	mem_inquiry_rcv                         	0x0013
#define	mem_fw_ver                              	0x0014
#define	mem_current_context                     	0x0015
#define	mem_empty_block                         	0x0016
#define	mem_last_freq                           	0x0017
#define	mem_rssi                                	0x0018
#define	mem_rx_type                             	0x0019
#define	mem_rx_hec_err                          	0x001a
#define	mem_rx_crc_err                          	0x001c
#define	mem_context_ptr                         	0x001e
#define	mem_display                             	0x0020
#define	mem_bcd                                 	0x0028
#define	mem_state                               	0x0030
#define	mem_mode                                	0x0031
#define	mem_tsniff                              	0x0032
#define	mem_sniff_anchor                        	0x0034
#define	mem_clk_offset                          	0x0038
#define	mem_rx_window                           	0x003e
#define	mem_plap                                	0x0040
#define	mem_puap                                	0x0043
#define	mem_pnap                                	0x0044
#define	mem_conn_handle                         	0x0046
#define	mem_cur_arq                             	0x0047
#define	mem_lmp_to_send                         	0x0048
#define	mem_lmi_opcode                          	0x0049
#define	mem_lmo_reason                          	0x004a
#define	mem_op                                  	0x004b
#define	mem_state_map                           	0x004c
#define	mem_supervision_timer                   	0x004d
#define	mem_supervision_to                      	0x0051
#define	mem_name_offset                         	0x0053
#define	mem_key_size                            	0x0054
#define	mem_reconn_lmp_sm                       	0x0055
#define	mem_aco                                 	0x0056
#define	mem_kc                                  	0x0062
#define	mem_conn_timer                          	0x0072
#define	mem_sniff_attempt                       	0x0073
#define	mem_sniff_timeout                       	0x0074
#define	mem_dsniff                              	0x0075
#define	mem_amaddr                              	0x0077
#define	mem_lmo_opcode1                         	0x0078
#define	mem_lmi_opcode1                         	0x0079
#define	mem_lmo_reason1                         	0x007a
#define	mem_lmo_tid1                            	0x007b
#define	mem_lmo_opcode2                         	0x007c
#define	mem_lmi_opcode2                         	0x007d
#define	mem_lmo_reason2                         	0x007e
#define	mem_lmo_tid2                            	0x007f
#define	mem_mark_load                           	0x0080
#define	mem_hci_version                         	0x0088
#define	mem_acl_pktlen                          	0x008b
#define	mem_sco_pktlen                          	0x008d
#define	mem_acl_pktcnt                          	0x008e
#define	mem_sco_pktcnt                          	0x0090
#define	mem_current_sniff_attempt               	0x0092
#define	mem_current_sniff_timeout               	0x0093
#define	mem_nfreq_index_inq                     	0x0094
#define	mem_nfreq_index_page                    	0x0095
#define	mem_ninqy_index                         	0x0096
#define	mem_fhs_misc                            	0x0097
#define	mem_tx_lch                              	0x0098
#define	mem_tx_len                              	0x0099
#define	mem_subsniff_instant                    	0x009b
#define	mem_subsniff_rate                       	0x009f
#define	mem_subsniff_tcmax                      	0x00a0
#define	mem_subsniff_tsniff                     	0x00a2
#define	mem_lpm_adjust                          	0x00a3
#define	mem_sync_clke                           	0x00a4
#define	mem_lpm_current_mult                    	0x00aa
#define	mem_gpio_wakeup_low                     	0x00ab
#define	mem_gpio_wakeup_high                    	0x00af
#define	mem_npage_index                         	0x00b3
#define	mem_page_mode                           	0x00b4
#define	mem_page_clk                            	0x00b5
#define	mem_tst_pktcnt_sync                     	0x00b9
#define	mem_tst_pktcnt_hec                      	0x00bb
#define	mem_tst_pktcnt_crc                      	0x00bd
#define	mem_tst_pktcnt_dmh                      	0x00bf
#define	mem_tmp_buffer_head                     	0x00c1
#define	mem_tmp_buffer                          	0x00c4
#define	mem_tester_emulate                      	0x0114
#define	mem_temp_payload                        	0x0115
#define	test_mode_scenario                      	0x0115
#define	test_mode_hopping_mode                  	0x0116
#define	test_mode_tx_freq                       	0x0117
#define	test_mode_rx_freq                       	0x0118
#define	test_mode_power_mode                    	0x0119
#define	test_mode_poll_period                   	0x011a
#define	test_mode_packet_type                   	0x011b
#define	test_mode_data_length                   	0x011c
#define	mem_test_mode_old_debug_config          	0x011e
#define	mem_tester_cnt                          	0x011f
#define	mem_temp_am_addr                        	0x0120
#define	mem_temp_arq                            	0x0121
#define	mem_pdatatemp                           	0x0122
#define	mem_len                                 	0x012a
#define	mem_clkn_bt                             	0x012c
#define	mem_clke_bt                             	0x0130
#define	mem_dpll_clkn                           	0x0134
#define	mem_connection_options                  	0x0138
#define	mem_nameres_cnt                         	0x0139
#define	mem_txptr                               	0x013a
#define	mem_slot_offset                         	0x013c
#define	extm_fhs_misc                           	0x013e
#define	extm_newconn_am_addr                    	0x013f
#define	extm_class                              	0x0140
#define	extm_lap                                	0x0143
#define	extm_uap                                	0x0146
#define	extm_nap                                	0x0147
#define	mem_debug_config                        	0x014a
#define	mem_lch_code                            	0x014b
#define	mem_fhs_am_addr                         	0x014c
#define	mem_dpll_error                          	0x014d
#define	mem_bdaddr_list_buff                    	0x014f
#define	mem_select_list_item                    	0x0173
#define	mem_temp_reconn_record                  	0x0174
#define	mem_record_bt_mode                      	0x0174
#define	mem_temp_lap                            	0x0175
#define	mem_list_item_ptr                       	0x017b
#define	mem_eir                                 	0x017d
#define	mem_switch_timeout                      	0x01e1
#define	mem_acl_dsniff                          	0x01e3
#define	mem_acl_tsniff                          	0x01e5
#define	mem_acl_attempt                         	0x01e7
#define	mem_acl_timeout                         	0x01e8
#define	mem_avdtp_signal_cmd                    	0x01e9
#define	mem_transaction_label                   	0x01ea
#define	mem_ucode_status                        	0x01eb
#define	mem_otp_ucode_flag                      	0x01ec
#define	mem_qspi_tbuf                           	0x01ee
#define	mem_iicd_tbuf                           	0x01ef
#define	mem_addr_hi                             	0x01ef
#define	mem_eep_addr_hi                         	0x01f0
#define	mem_addr_mi                             	0x01f0
#define	mem_addr_lo                             	0x01f1
#define	mem_iicd_addr                           	0x01f2
#define	mem_spid_rbuf                           	0x01f3
#define	mem_ucode_buf                           	0x01f7
#define	mem_ucode_len                           	0x01f9
#define	mem_sched_addr                          	0x01fb
#define	mem_ucode_ptr                           	0x01fd
#define	mem_ucode_keybuf                        	0x0200
#define	mem_check_plap_temp                     	0x0210
#define	mem_spid_tbuf                           	0x0222
#define	mem_sensor_id                           	0x0224
#define	mem_switch_fail_master_count            	0x0225
#define	mem_app_evt_timer_count                 	0x0226
#define	mem_h5rx_ackcnt                         	0x0227
#define	mem_check_err_acl_cont                  	0x0228
#define	mem_rp_packets                          	0x0229
#define	mem_packet_type                         	0x022a
#define	mem_hci_sniff_conn_handle               	0x022c
#define	mem_hci_sniff_max_interval              	0x022e
#define	mem_hci_sniff_min_interval              	0x0230
#define	mem_hci_sniff_attempt                   	0x0232
#define	mem_hci_sniff_timeout                   	0x0234
#define	mem_voice_setting                       	0x0236
#define	mem_retransmission_effort               	0x0238
#define	mem_sco_ptype                           	0x0239
#define	mem_extm_uap_restore                    	0x023b
#define	mem_h5rx_rptr                           	0x023e
#define	mem_h5rx_ack                            	0x0240
#define	mem_h5tx_ack                            	0x0241
#define	mem_h5tx_rptr                           	0x0242
#define	mem_h5tx_wptr                           	0x0244
#define	mem_h5tx_free                           	0x0246
#define	mem_h5rx_tmp                            	0x0248
#define	mem_h5tx_seq                            	0x0249
#define	mem_hci_acl_queue_wptr                  	0x024a
#define	mem_hci_acl_queue_rptr                  	0x024c
#define	mem_hci_acl_queue_end                   	0x024e
#define	mem_hci_acl_queue_wcnt                  	0x0250
#define	mem_hci_acl_cnt                         	0x0251
#define	mem_hci_acl_tx_trigger_wptr             	0x0252
#define	mem_ucode_id_local                      	0x0254
#define	mem_ucode_id_remote                     	0x0255
#define	mem_check_sum                           	0x0256
#define	mem_ucode_temp                          	0x0257
#define	mem_ucode_temp1                         	0x0258
#define	mem_lock_in_enc                         	0x0259
#define	mem_hci_disconn_reason                  	0x025a
#define	mem_hci_curr_len                        	0x025b
#define	mem_hci_curr_target                     	0x025c
#define	mem_audio_size                          	0x025e
#define	mem_audio_offset                        	0x0260
#define	mem_sco_indata                          	0x0262
#define	mem_sco_outdata                         	0x029e
#define	mem_phone_num_len                       	0x02da
#define	mem_phone_number                        	0x02db
#define	mem_at_command_data                     	0x02ea
#define	mem_sco_flag                            	0x0308
#define	mem_l2cap_mem_start                     	0x0309
#define	mem_l2cap_rxbuff1_len                   	0x0309
#define	mem_l2cap_rxbuff2_len                   	0x030b
#define	mem_l2cap_rxbuff_new                    	0x030d
#define	mem_l2cap_rxbuff_fifo                   	0x030f
#define	mem_l2cap_rxbuff_fifo1                  	0x030f
#define	mem_l2cap_rxbuff_fifo2                  	0x0310
#define	mem_l2cap_payload_ptr                   	0x0311
#define	mem_l2cap_rx_pkt_length                 	0x0313
#define	mem_l2cap_rx_cid                        	0x0315
#define	mem_l2cap_rx_done                       	0x0317
#define	mem_l2cap_signal_ident                  	0x0318
#define	mem_sdp_tx_buff_ptr                     	0x0319
#define	mem_sdp_tx_payload_ptr                  	0x031b
#define	mem_sdp_tx_pkt_length                   	0x031d
#define	mem_tx_malloc_log                       	0x031f
#define	mem_l2cap_temp_ch_info                  	0x035f
#define	mem_l2cap_temp_ch_psm                   	0x035f
#define	mem_l2cap_temp_ch_state                 	0x0360
#define	mem_l2cap_temp_local_cid                	0x0361
#define	mem_l2cap_temp_remote_cid               	0x0363
#define	mem_l2cap_mem_end                       	0x0365
#define	mem_le_rxbuf                            	0x0365
#define	mem_le_l2capbuf                         	0x038d
#define	mem_le_mic                              	0x0465
#define	mem_le_peer_mic                         	0x0469
#define	mem_le_skdm                             	0x046d
#define	mem_le_skds                             	0x0475
#define	mem_le_peer_ltk                         	0x047d
#define	mem_le_my_ltk                           	0x048d
#define	mem_le_mrand                            	0x049d
#define	mem_le_state                            	0x04ad
#define	mem_le_mode                             	0x04ae
#define	mem_le_tsniff                           	0x04af
#define	mem_le_anchor                           	0x04b1
#define	mem_le_clk_offset                       	0x04b5
#define	mem_le_receive_window                   	0x04bb
#define	mem_le_plap                             	0x04bd
#define	mem_le_conn_handle                      	0x04c3
#define	mem_le_arq                              	0x04c4
#define	mem_le_ch                               	0x04c5
#define	mem_le_hop                              	0x04c6
#define	mem_le_event_count                      	0x04c7
#define	mem_le_supervision_timer                	0x04c9
#define	mem_le_instant                          	0x04cd
#define	mem_le_channels                         	0x04cf
#define	mem_le_conn_sm                          	0x04d0
#define	mem_le_op                               	0x04d1
#define	mem_le_access                           	0x04d2
#define	mem_le_crcinit                          	0x04d6
#define	mem_le_window_size                      	0x04d9
#define	mem_le_slave_latency                    	0x04da
#define	mem_le_superto                          	0x04dc
#define	mem_le_channel_map                      	0x04de
#define	mem_le_no_using                         	0x04e3
#define	mem_le_peer_sca                         	0x04e5
#define	mem_le_att_opcode                       	0x04e6
#define	mem_le_att_handle                       	0x04e7
#define	mem_le_err_code                         	0x04e9
#define	mem_le_ll_pairing_fail_reason           	0x04ea
#define	mem_le_sk                               	0x04eb
#define	mem_le_testtype                         	0x04fb
#define	mem_le_test_sync                        	0x04fc
#define	mem_le_test_pcnt                        	0x04fe
#define	mem_le_notify_len                       	0x0500
#define	mem_cmd_le_create_conn                  	0x0501
#define	mem_le_adv_temp                         	0x0502
#define	mem_le_packet_size                      	0x0516
#define	mem_le_packet_llid                      	0x0517
#define	mem_le_payload_ptr                      	0x0518
#define	mem_lmo_header_length                   	0x051a
#define	mem_lmo_header_opcode                   	0x051b
#define	mem_lmo_payload                         	0x051c
#define	mem_lmi_accepted_opcode                 	0x052d
#define	mem_disconn_reason_send                 	0x052e
#define	mem_tx_fixed_freq                       	0x052f
#define	mem_rx_fixed_freq                       	0x0530
#define	mem_ext_features_page                   	0x0531
#define	mem_lmpext_ssp_enable                   	0x0532
#define	mem_remote_sppcap                       	0x0534
#define	mem_lmp_conn_state                      	0x0535
#define	mem_soft_timer                          	0x0536
#define	mem_pincode_state                       	0x0538
#define	mem_sres_tid                            	0x0539
#define	mem_accptsco_tid                        	0x053a
#define	mem_wait_encryption                     	0x053b
#define	mem_sniff_payload                       	0x053c
#define	mem_aurand_send_delay_time              	0x054c
#define	mem_prcp_data                           	0x0550
#define	mem_prcp                                	0x0564
#define	mem_prcp_tx_len                         	0x0565
#define	rx_buf_data_ptr                         	0x0566
#define	mem_mod2div_temp                        	0x0568
#define	mem_contw_temp                          	0x056b
#define	mem_rfc_adss                            	0x056d
#define	mem_rfc_current_channel                 	0x056e
#define	mem_rfc_frame_type                      	0x056f
#define	mem_current_fcs                         	0x0570
#define	mem_rfc_paylead_length                  	0x0571
#define	mem_rfc_paylead_ptr                     	0x0573
#define	mem_uih_cmd_type                        	0x0575
#define	mem_uih_length                          	0x0576
#define	mem_rfc_payload_ptr                     	0x0578
#define	mem_ms_param                            	0x057a
#define	mem_pn_credit_flow_type_info            	0x057b
#define	mem_pn_priority                         	0x057c
#define	mem_pn_acknowledg_timer                 	0x057d
#define	mem_pn_max_retrans                      	0x057e
#define	mem_rfcomm_send_adss                    	0x057f
#define	mem_rfcomm_send_frame_type              	0x0580
#define	mem_rfcomm_send_fcs                     	0x0581
#define	mem_sdp_mem_start                       	0x0582
#define	mem_sdp_uuid_search_ptr                 	0x0582
#define	mem_sdp_continue_byte                   	0x058a
#define	mem_sdp_pduid                           	0x058c
#define	mem_sdp_transactionid                   	0x058d
#define	mem_sdp_transactionid_local             	0x058f
#define	mem_sdp_attribute_maxbyte               	0x0591
#define	mem_sdp_record_maxcnt                   	0x0593
#define	mem_sdp_record_handle                   	0x0595
#define	mem_sdp_LACAP_found                     	0x0599
#define	mem_sdp_RFCOMM_found                    	0x059a
#define	mem_sdp_handle_list                     	0x059b
#define	mem_sdp_attrib_list                     	0x059b
#define	mem_sdp_error_code                      	0x05bb
#define	mem_sdp_all_length                      	0x05bd
#define	mem_handle_humber                       	0x05bf
#define	mem_search_uuid                         	0x05c0
#define	mem_sdp_mem_end                         	0x05c2
#define	mem_rxbuf                               	0x05c2
#define	mem_random_number                       	0x05d3
#define	mem_round_key                           	0x05e3
#define	mem_kinit                               	0x05f3
#define	mem_input_store                         	0x0603
#define	mem_x                                   	0x0613
#define	mem_y                                   	0x0623
#define	mem_y15                                 	0x0632
#define	mem_key_store                           	0x0633
#define	mem_key_store_end                       	0x0644
#define	memp_ar_key                             	0x0645
#define	memp_ar_input                           	0x0647
#define	mem_ar_hround                           	0x0649
#define	mem_ec_infinite                         	0x0653
#define	mem_ec_loopc                            	0x0654
#define	mem_aes_cmac_data_length                	0x0656
#define	memdat                                  	0x0657
#define	mem_ax                                  	0x0657
#define	mem_ay                                  	0x066f
#define	mem_az                                  	0x0687
#define	mem_bx                                  	0x069f
#define	mem_ax_256                              	0x06b7
#define	mem_by                                  	0x06b7
#define	mem_bz                                  	0x06cf
#define	mem_ay_256                              	0x06d7
#define	mem_cx                                  	0x06e7
#define	mem_az_256                              	0x06f7
#define	mem_cy                                  	0x06ff
#define	mem_cy5                                 	0x0716
#define	mem_bx_256                              	0x0717
#define	mem_cz                                  	0x0717
#define	mem_k                                   	0x072f
#define	mem_by_256                              	0x0737
#define	mem_align                               	0x0747
#define	mem_bz_256                              	0x0757
#define	mem_tmp1                                	0x0757
#define	memahbak                                	0x0757
#define	mem_tmp5                                	0x076f
#define	mem_cx_256                              	0x0777
#define	memahsave                               	0x0777
#define	mem_tmp2                                	0x0787
#define	mem_cy_256                              	0x0797
#define	memahsave_end                           	0x0797
#define	mem_addr_padding                        	0x0797
#define	mem_addr_value                          	0x0798
#define	mem_tmp3                                	0x079f
#define	mem_t1                                  	0x079f
#define	mem_addr_value_end                      	0x07a4
#define	mem_addr_iocap_end                      	0x07a7
#define	mem_cy5_256                             	0x07b6
#define	mem_cz_256                              	0x07b7
#define	mem_tmp0                                	0x07b7
#define	mem_t0                                  	0x07b7
#define	mem_tmp0a                               	0x07bf
#define	mem_t2                                  	0x07cf
#define	mem_k_256                               	0x07d7
#define	mem_t3                                  	0x07e7
#define	mem_tmp1_256                            	0x07f7
#define	mem_t7                                  	0x07ff
#define	mem_tmp5_256                            	0x0817
#define	mem_tmp2_256                            	0x0837
#define	mem_tmp3_256                            	0x0857
#define	mem_t1_256                              	0x0857
#define	mem_tmp0_256                            	0x0877
#define	mem_t0_256                              	0x0877
#define	mem_t2_256                              	0x0897
#define	mem_t3_256                              	0x08b7
#define	mem_t7_256                              	0x08d7
#define	mem_p                                   	0x08f7
#define	mem_a                                   	0x090f
#define	mem_b                                   	0x0927
#define	mem_gx                                  	0x093f
#define	mem_gy                                  	0x0957
#define	memh0                                   	0x096f
#define	mem_p_256                               	0x098f
#define	mem_a_256                               	0x09af
#define	mem_gx_256                              	0x09cf
#define	mem_gy_256                              	0x09ef
#define	mem_le_slat                             	0x0a0f
#define	mem_sp_state_start                      	0x0a1f
#define	mem_sp_state                            	0x0a1f
#define	mem_master_sp_state                     	0x0a20
#define	mem_sp_flag                             	0x0a21
#define	mem_master_sp_flag                      	0x0a22
#define	mem_sp_calc                             	0x0a23
#define	mem_sp_dh_ready                         	0x0a24
#define	mem_sp_localsm                          	0x0a25
#define	mem_pairing_auth                        	0x0a26
#define	mem_sp_flag_start                       	0x0a27
#define	mem_sp_local_key_send_count             	0x0a27
#define	mem_sp_remote_key_recv_count            	0x0a28
#define	mem_sp_remote_key_invalid               	0x0a29
#define	mem_sp_dhkey_invalid                    	0x0a2a
#define	mem_gkey                                	0x0a2b
#define	mem_le_pubkey_remote_x_256              	0x0a2f
#define	mem_sp_pubkey_remote                    	0x0a37
#define	mem_sp_pubkey_remote_x                  	0x0a37
#define	mem_sp_pubkey_remote_x_end              	0x0a4f
#define	mem_sp_pubkey_remote_y                  	0x0a4f
#define	mem_le_pubkey_remote_y_256              	0x0a4f
#define	mem_le_dhkey_256                        	0x0a6f
#define	mem_sp_dhkey                            	0x0a77
#define	mem_sp_dhkey_end                        	0x0a8f
#define	mem_sp_random_local                     	0x0a8f
#define	mem_sp_random_local_end                 	0x0a9f
#define	mem_sp_random_remote                    	0x0a9f
#define	mem_sp_random_remote_end                	0x0aaf
#define	memresult                               	0x0aaf
#define	mem_sp_calc_result                      	0x0aaf
#define	memh                                    	0x0aaf
#define	memg                                    	0x0ab3
#define	memf                                    	0x0ab7
#define	meme                                    	0x0abb
#define	mem_sp_calc_result_high                 	0x0abf
#define	memd                                    	0x0abf
#define	memc                                    	0x0ac3
#define	memb                                    	0x0ac7
#define	mema                                    	0x0acb
#define	mem_sp_check_result                     	0x0acf
#define	mem_sp_confirm_remote                   	0x0adf
#define	mem_sp_prarm_stack                      	0x0aef
#define	mem_ipc_skip_continue_proc              	0x0aff
#define	mem_ipc_rega_temp                       	0x0b00
#define	mem_hold_contr                          	0x0b04
#define	mem_hold_contw                          	0x0b06
#define	mem_fifo_temp                           	0x0b08
#define	mem_max_bitsneed                        	0x0b09
#define	mem_bits_need00                         	0x0b0d
#define	mem_temp                                	0x0b0d
#define	mem_bits_need01                         	0x0b11
#define	mem_temp1                               	0x0b11
#define	mem_bits_need02                         	0x0b15
#define	mem_timeup                              	0x0b15
#define	mem_bits_need03                         	0x0b19
#define	mem_rega                                	0x0b19
#define	mem_bits_need04                         	0x0b1d
#define	mem_regb                                	0x0b1d
#define	mem_bits_need05                         	0x0b21
#define	mem_regc                                	0x0b21
#define	mem_bits_need06                         	0x0b25
#define	mem_contr                               	0x0b25
#define	mem_contw                               	0x0b27
#define	mem_bits_need07                         	0x0b29
#define	mem_bits_need10                         	0x0b2d
#define	mem_bits_need11                         	0x0b31
#define	mem_bits_need12                         	0x0b35
#define	mem_bits_need13                         	0x0b39
#define	mem_bits_need14                         	0x0b3d
#define	mem_bits_need15                         	0x0b41
#define	mem_bits_need16                         	0x0b45
#define	mem_bits_need17                         	0x0b49
#define	mem_flash_address                       	0x0b4d
#define	mem_flash_data_address                  	0x0b50
#define	mem_flash_trans_length                  	0x0b52
#define	mem_le_data_len_temp                    	0x0b54
#define	mem_tx_fifo_map_temp                    	0x0b54
#define	mem_rpn_dlci                            	0x0b54
#define	mem_event_cmd_response_content          	0x0b54
#define	mem_le_prand                            	0x0b54
#define	mem_AES_CMAC_k                          	0x0b54
#define	mem_regext_index                        	0x0b54
#define	mem_temp_block0                         	0x0b54
#define	mem_le_data_temp                        	0x0b55
#define	mem_temp_block1                         	0x0b55
#define	mem_le_aes_128                          	0x0b64
#define	mem_regext                              	0x0b64
#define	mem_AES_CMAC_k1                         	0x0b64
#define	mem_temp_block2                         	0x0b64
#define	mem_AES_CMAC_k2                         	0x0b74
#define	mem_temp_block3                         	0x0b74
#define	mem_AES_CMAC_temp                       	0x0b84
#define	mem_temp_block4                         	0x0b84
#define	mem_AES_CMAC_M_last                     	0x0b94
#define	mem_temp_block5                         	0x0b94
#define	mem_le_mackey                           	0x0ba4
#define	mem_temp_block6                         	0x0ba4
#define	mem_aes_state_map                       	0x0bb4
#define	mem_aes_type                            	0x0bb5
#define	mem_tws_sync_clk                        	0x0bb7
#define	mem_tws_connecting_phase                	0x0bbb
#define	mem_tws_context_offset                  	0x0bbc
#define	mem_patch00                             	0x4000
#define	mem_patch01                             	0x4001
#define	mem_patch02                             	0x4002
#define	mem_patch03                             	0x4003
#define	mem_patch04                             	0x4004
#define	mem_patch05                             	0x4005
#define	mem_patch06                             	0x4006
#define	mem_patch07                             	0x4007
#define	mem_patch08                             	0x4008
#define	mem_patch09                             	0x4009
#define	mem_patch0a                             	0x400a
#define	mem_patch0b                             	0x400b
#define	mem_patch0c                             	0x400c
#define	mem_patch0d                             	0x400d
#define	mem_patch0e                             	0x400e
#define	mem_patch0f                             	0x400f
#define	mem_patch10                             	0x4010
#define	mem_patch11                             	0x4011
#define	mem_patch12                             	0x4012
#define	mem_patch13                             	0x4013
#define	mem_patch14                             	0x4014
#define	mem_patch15                             	0x4015
#define	mem_patch16                             	0x4016
#define	mem_patch17                             	0x4017
#define	mem_patch18                             	0x4018
#define	mem_patch19                             	0x4019
#define	mem_patch1a                             	0x401a
#define	mem_patch1b                             	0x401b
#define	mem_patch1c                             	0x401c
#define	mem_patch1d                             	0x401d
#define	mem_patch1e                             	0x401e
#define	mem_patch1f                             	0x401f
#define	mem_patch20                             	0x4020
#define	mem_patch21                             	0x4021
#define	mem_patch22                             	0x4022
#define	mem_patch23                             	0x4023
#define	mem_patch24                             	0x4024
#define	mem_patch25                             	0x4025
#define	mem_patch26                             	0x4026
#define	mem_patch27                             	0x4027
#define	mem_patch28                             	0x4028
#define	mem_patch29                             	0x4029
#define	mem_patch2a                             	0x402a
#define	mem_patch2b                             	0x402b
#define	mem_patch2c                             	0x402c
#define	mem_patch2d                             	0x402d
#define	mem_patch2e                             	0x402e
#define	mem_patch2f                             	0x402f
#define	mem_patch30                             	0x4030
#define	mem_patch31                             	0x4031
#define	mem_patch32                             	0x4032
#define	mem_patch33                             	0x4033
#define	mem_patch34                             	0x4034
#define	mem_patch35                             	0x4035
#define	mem_patch36                             	0x4036
#define	mem_patch37                             	0x4037
#define	mem_patch38                             	0x4038
#define	mem_patch39                             	0x4039
#define	mem_patch3a                             	0x403a
#define	mem_patch3b                             	0x403b
#define	mem_patch3c                             	0x403c
#define	mem_patch3d                             	0x403d
#define	mem_patch3e                             	0x403e
#define	mem_patch3f                             	0x403f
#define	mem_context                             	0x4040
#define	mem_current_amaddr                      	0x4130
#define	mem_lpm_mode                            	0x4131
#define	mem_device_option                       	0x4132
#define	mem_scan_mode                           	0x4133
#define	mem_last_clkn                           	0x4134
#define	mem_features                            	0x4138
#define	mem_lap                                 	0x4140
#define	mem_uap                                 	0x4143
#define	mem_nap                                 	0x4144
#define	mem_npage                               	0x4146
#define	mem_glap                                	0x4147
#define	mem_class                               	0x414a
#define	mem_iscan_window                        	0x414d
#define	mem_iscan_interval                      	0x414f
#define	mem_pscan_window                        	0x4151
#define	mem_pscan_interval                      	0x4153
#define	mem_page_interval                       	0x4155
#define	mem_page_window                         	0x4157
#define	mem_page_to                             	0x4159
#define	mem_inq_window                          	0x415b
#define	mem_fcomp_mul                           	0x415d
#define	mem_fcomp_div                           	0x415e
#define	mem_rx_window_init                      	0x415f
#define	mem_rx_window_sniff                     	0x4161
#define	mem_rf_init_ptr                         	0x4163
#define	mem_last_type                           	0x4165
#define	mem_retransmission_cnt                  	0x4166
#define	mem_next_btclk                          	0x4168
#define	mem_seqi                                	0x416c
#define	mem_rf_rccal                            	0x416d
#define	mem_handle_num                          	0x416e
#define	mem_max_slot                            	0x416f
#define	mem_eir_enable                          	0x4170
#define	mem_afh_instant                         	0x4171
#define	mem_afh_error_total                     	0x4175
#define	mem_afh_cfg                             	0x4177
#define	mem_afh_new_mod                         	0x4178
#define	mem_afh_map_lo                          	0x4179
#define	mem_afh_map_hi                          	0x417e
#define	mem_afh_used                            	0x4183
#define	mem_afh_index                           	0x4184
#define	mem_afh_map_new                         	0x4186
#define	mem_afh_map                             	0x4191
#define	mem_afh_timer                           	0x41e1
#define	mem_afh_classify_channel_map            	0x41e5
#define	mem_chip_functions                      	0x41ef
#define	mem_lpm_wake_lock                       	0x41f1
#define	mem_lpm_interval                        	0x41f3
#define	mem_lpm_overhead                        	0x41f5
#define	mem_lpm_hibernate_switch                	0x41f6
#define	mem_sniff_unint_lost                    	0x41f7
#define	mem_ptt                                 	0x41f8
#define	mem_sleep_counter                       	0x41f9
#define	mem_sleep_counter_all                   	0x41fd
#define	mem_sleep_clkn                          	0x4201
#define	mem_sniff_rcv                           	0x4207
#define	mem_sniff_lost                          	0x420a
#define	mem_clks_per_lpo                        	0x420d
#define	mem_lpm_mult                            	0x4210
#define	mem_lpm_mult_timeout                    	0x4211
#define	mem_lpm_mult_cnt                        	0x4212
#define	mem_lpm_config                          	0x4213
#define	mem_lpm_xtalcnt                         	0x4216
#define	mem_lpm_buckcnt                         	0x4217
#define	mem_lpm_ldocnt                          	0x4218
#define	mem_lpm_isogate                         	0x4219
#define	mem_lpm_isogate_final                   	0x421a
#define	mem_saved_gpio                          	0x421b
#define	mem_saved_mark                          	0x4243
#define	mem_saved_spidctrl                      	0x424b
#define	mem_patch_ptr                           	0x424c
#define	mem_patch_len                           	0x424e
#define	mem_timers                              	0x4250
#define	mem_link_key_exists                     	0x4270
#define	mem_link_key_eeprom_head                	0x4271
#define	mem_link_key                            	0x4274
#define	mem_hci_cmd                             	0x4284
#define	mem_hci_conn_handle                     	0x4285
#define	mem_hci_plap                            	0x4286
#define	mem_hci_puap                            	0x4289
#define	mem_hci_pnap                            	0x428a
#define	mem_uartd_rxitems_got_data              	0x428c
#define	mem_uartd_rxitems_threshold             	0x428d
#define	mem_uartd_rx_timeout                    	0x428e
#define	mem_sco_attempt_cout                    	0x4290
#define	mem_tx_power                            	0x4291
#define	mem_avdtp_xmem_start                    	0x4292
#define	mem_avdtpsignal_l2capch_ptr             	0x4292
#define	mem_avdtpmedia_l2capch_ptr              	0x4294
#define	mem_audio_allow                         	0x4296
#define	mem_audio_state                         	0x4297
#define	mem_audio_src_endpoint                  	0x4298
#define	mem_audio_src_endpoint_state            	0x4299
#define	mem_a2dp_reconnct_delay_timer           	0x429a
#define	mem_avdtp_xmem_end                      	0x429b
#define	mem_avdtp_codec_type                    	0x429b
#define	mem_conf_codec_type                     	0x42a1
#define	mem_conf_channel_mode                   	0x42a2
#define	mem_conf_sample_freq                    	0x42a3
#define	mem_conf_allocation_method              	0x42a4
#define	mem_conf_subbands                       	0x42a5
#define	mem_conf_blocklen                       	0x42a6
#define	mem_conf_min_poolval                    	0x42a7
#define	mem_conf_max_poolval                    	0x42a8
#define	mem_opend_seid                          	0x42a9
#define	mem_started_seid                        	0x42aa
#define	mem_avc_local_transaction_label         	0x42ab
#define	mem_audio_vol                           	0x42ac
#define	mem_avdtp_signal                        	0x42ad
#define	mem_avdtp_media                         	0x42af
#define	mem_app_state                           	0x42b1
#define	mem_app_handshake_flag                  	0x42b2
#define	mem_sniff_param_interval                	0x42b3
#define	mem_sniff_param_attempt                 	0x42b5
#define	mem_sniff_param_timeout                 	0x42b7
#define	mem_cb_check_wakelock                   	0x42b9
#define	mem_cb_before_hibernate                 	0x42bb
#define	mem_cb_before_lpm                       	0x42bd
#define	mem_cb_le_process                       	0x42bf
#define	mem_cb_bt_process                       	0x42c1
#define	mem_cb_idle_process                     	0x42c3
#define	mem_cb_bb_event_process                 	0x42c5
#define	mem_device_nums                         	0x42c7
#define	mem_uart_txpin                          	0x42c8
#define	mem_uart_rxpin                          	0x42c9
#define	mem_uart_rtspin                         	0x42ca
#define	mem_uart_ctspin                         	0x42cb
#define	mem_uartb_txpin                         	0x42cc
#define	mem_uartb_rxpin                         	0x42cd
#define	mem_uartb_rtspin                        	0x42ce
#define	mem_uartb_ctspin                        	0x42cf
#define	mem_spid_sclkpin                        	0x42d0
#define	mem_spid_sdiopin                        	0x42d1
#define	mem_ef_base                             	0x42d2
#define	mem_eeprom_block_size                   	0x42d5
#define	mem_app_connection_options              	0x42d7
#define	mem_app_disconn_reason                  	0x42d8
#define	mem_app_disconn_reason_flag             	0x42da
#define	mem_xip_flash_offset                    	0x42dc
#define	mem_xip_option                          	0x42df
#define	mem_xip_flash_read_cmd                  	0x42e1
#define	mem_nv_data_ptr                         	0x42e2
#define	mem_nv_data_number                      	0x42e4
#define	mem_discory_timer                       	0x42e5
#define	mem_avctp_xmem_start                    	0x42e6
#define	mem_avctp_trans_lable                   	0x42e6
#define	mem_avr_state                           	0x42e7
#define	mem_avr_l2capch_ptr                     	0x42e8
#define	mem_avctp_xmem_end                      	0x42ea
#define	mem_cvsd_in_addr_end                    	0x42ea
#define	mem_cvsd_in_addr_ptr                    	0x42ec
#define	mem_cvsd_out_addr_end                   	0x42ee
#define	mem_cvsd_out_addr_ptr                   	0x42f0
#define	mem_baud                                	0x42f2
#define	mem_hci_lt_rx_state                     	0x42f4
#define	mem_hid_xmem_start                      	0x42f5
#define	mem_hid_l2capch_ptr                     	0x42f5
#define	mem_hidint_l2capch_ptr                  	0x42f7
#define	mem_hid_xmem_end                        	0x42f9
#define	mem_xmem_sco_start                      	0x42f9
#define	mem_sco_asso_handle                     	0x42f9
#define	mem_sco_handle                          	0x42fa
#define	mem_sco_dsniff                          	0x42fc
#define	mem_sco_tsniff                          	0x42fe
#define	mem_sco_wsniff                          	0x4300
#define	mem_sco_tx_packet_type                  	0x4301
#define	mem_sco_rx_packet_type                  	0x4302
#define	mem_sco_rx_packet_len                   	0x4303
#define	mem_sco_tx_packet_len                   	0x4305
#define	mem_air_mode                            	0x4307
#define	mem_neogotiation_state                  	0x4308
#define	mem_acl_amaddr                          	0x4309
#define	mem_esco_amaddr                         	0x430a
#define	mem_esco_arq                            	0x430b
#define	mem_acl_arq                             	0x430c
#define	mem_last_type_esco                      	0x430d
#define	mem_last_type_acl                       	0x430e
#define	mem_sco_poll                            	0x430f
#define	mem_esco_attempt                        	0x4310
#define	mem_esco_abnormal_attempt               	0x4311
#define	mem_xmem_sco_end                        	0x4312
#define	mem_xmem_hf_state_start                 	0x4312
#define	mem_hf_state                            	0x4312
#define	mem_hf_call_state                       	0x4313
#define	mem_hf_command                          	0x4314
#define	mem_agoption                            	0x4315
#define	mem_AG_indicator_map                    	0x4317
#define	mem_AG_indicator                        	0x431e
#define	mem_xmem_hf_state_end                   	0x4325
#define	mem_hf_vlm_speaker                      	0x4325
#define	mem_music_vlm_speaker                   	0x4326
#define	mem_hf_vlm_mic                          	0x4327
#define	mem_at_payload_ptr                      	0x4328
#define	mem_at_command_ptr                      	0x432a
#define	mem_at_rfcomm_data_ptr                  	0x432c
#define	memUI_HF_brsf_feature                   	0x432e
#define	mem_cb_hfp_result_code                  	0x4330
#define	mem_esco_test                           	0x4332
#define	mem_ipc_mcu_phase                       	0x4333
#define	mem_ipc_mcu_state                       	0x4334
#define	mem_ipc_enable                          	0x4335
#define	mem_ipc_le_data_len                     	0x4336
#define	mem_ipc_le_data_att_handle              	0x4337
#define	mem_ipc_tx_data_len                     	0x4339
#define	mem_ipc_tx_data_ptr                     	0x433a
#define	mem_ipc_loss_packet                     	0x433c
#define	mem_temp_for_addr                       	0x433e
#define	mem_ipc_test_buff                       	0x4341
#define	mem_l2cap_xmem_start                    	0x434b
#define	mem_l2cap_tx_multi_offset               	0x434b
#define	mem_l2cap_pending_info                  	0x434d
#define	mem_l2cap_pending_id0                   	0x434d
#define	mem_l2cap_pending_delay_time0           	0x434e
#define	mem_l2cap_pending_ptr0                  	0x4352
#define	mem_l2cap_pending_id1                   	0x4354
#define	mem_l2cap_pending_delay_time1           	0x4355
#define	mem_l2cap_pending_ptr1                  	0x4359
#define	mem_l2cap_pending_id2                   	0x435b
#define	mem_l2cap_pending_delay_time2           	0x435c
#define	mem_l2cap_pending_ptr2                  	0x4360
#define	mem_l2cap_pending_count                 	0x4362
#define	mem_l2cap_active_ch_count               	0x4363
#define	mem_l2cap_ch_info                       	0x4364
#define	mem_l2cap_ch_psm0                       	0x4364
#define	mem_l2cap_ch_state0                     	0x4365
#define	mem_l2cap_local_cid0                    	0x4366
#define	mem_l2cap_remote_cid0                   	0x4368
#define	mem_l2cap_ch_psm1                       	0x436a
#define	mem_l2cap_ch_state1                     	0x436b
#define	mem_l2cap_local_cid1                    	0x436c
#define	mem_l2cap_remote_cid1                   	0x436e
#define	mem_l2cap_ch_psm2                       	0x4370
#define	mem_l2cap_ch_state2                     	0x4371
#define	mem_l2cap_local_cid2                    	0x4372
#define	mem_l2cap_remote_cid2                   	0x4374
#define	mem_l2cap_ch_psm3                       	0x4376
#define	mem_l2cap_ch_state3                     	0x4377
#define	mem_l2cap_local_cid3                    	0x4378
#define	mem_l2cap_remote_cid3                   	0x437a
#define	mem_l2cap_ch_psm4                       	0x437c
#define	mem_l2cap_ch_state4                     	0x437d
#define	mem_l2cap_local_cid4                    	0x437e
#define	mem_l2cap_remote_cid4                   	0x4380
#define	mem_l2cap_ch_psm5                       	0x4382
#define	mem_l2cap_ch_state5                     	0x4383
#define	mem_l2cap_local_cid5                    	0x4384
#define	mem_l2cap_remote_cid5                   	0x4386
#define	mem_l2cap_ch_psm6                       	0x4388
#define	mem_l2cap_ch_state6                     	0x4389
#define	mem_l2cap_local_cid6                    	0x438a
#define	mem_l2cap_remote_cid6                   	0x438c
#define	mem_l2cap_ch_psm7                       	0x438e
#define	mem_l2cap_ch_state7                     	0x438f
#define	mem_l2cap_local_cid7                    	0x4390
#define	mem_l2cap_remote_cid7                   	0x4392
#define	mem_l2cap_prepare_confreq_count         	0x4394
#define	mem_l2cap_channel_disconnect_timer      	0x4395
#define	mem_sdp_state                           	0x4396
#define	mem_ML2CAP_comm_id                      	0x4397
#define	mem_used_map                            	0x4398
#define	mem_tx_fifo0                            	0x4399
#define	mem_tx_fifo0_map                        	0x4399
#define	mem_tx_fifo0_ptr                        	0x439a
#define	mem_tx_fifo1                            	0x439c
#define	mem_tx_fifo1_map                        	0x439c
#define	mem_tx_fifo1_ptr                        	0x439d
#define	mem_tx_fifo2                            	0x439f
#define	mem_tx_fifo2_map                        	0x439f
#define	mem_tx_fifo2_ptr                        	0x43a0
#define	mem_tx_fifo3                            	0x43a2
#define	mem_tx_fifo3_map                        	0x43a2
#define	mem_tx_fifo3_ptr                        	0x43a3
#define	mem_tx_fifo_end                         	0x43a5
#define	mem_l2cap_flow_ctrl_flag                	0x43a5
#define	mem_l2cap_pending_item                  	0x43a6
#define	mem_l2cap_xmem_end                      	0x43a7
#define	mem_le_dsniff                           	0x43a7
#define	mem_le_conn_interval                    	0x43a9
#define	mem_le_scan_enable                      	0x43ab
#define	mem_le_scan_interval                    	0x43ac
#define	mem_le_scan_window                      	0x43ae
#define	mem_le_adv_led                          	0x43b0
#define	mem_le_adv_enable                       	0x43b1
#define	mem_le_adv_data_len                     	0x43b2
#define	mem_le_adv_data                         	0x43b3
#define	mem_le_scan_data_len                    	0x43d2
#define	mem_le_scan_data                        	0x43d3
#define	mem_le_interal_min                      	0x43f2
#define	mem_le_interal_max                      	0x43f4
#define	mem_le_latency                          	0x43f6
#define	mem_le_timeout                          	0x43f8
#define	mem_le_ch_mapped                        	0x43fa
#define	mem_le_new_map                          	0x43fb
#define	mem_le_new_param                        	0x4400
#define	mem_le_txheader                         	0x4409
#define	mem_le_txlen                            	0x440a
#define	mem_le_txpayload                        	0x440b
#define	mem_le_txcid                            	0x440d
#define	mem_le_l2cap                            	0x440f
#define	mem_le_l2cap_response                   	0x4410
#define	mem_le_txbdy                            	0x4411
#define	mem_le_pcnt_tx                          	0x4430
#define	mem_le_pcnt_rx                          	0x4435
#define	mem_le_last_mic                         	0x443a
#define	mem_le_ivm                              	0x443e
#define	mem_le_ivs                              	0x4442
#define	mem_le_ltk                              	0x4446
#define	mem_ltk_exists                          	0x4456
#define	mem_le_rconfirm                         	0x4457
#define	mem_le_srand                            	0x4467
#define	mem_le_iat                              	0x4477
#define	mem_le_rat                              	0x4478
#define	mem_le_preq                             	0x4479
#define	mem_le_preq_iocap                       	0x447a
#define	mem_le_preq_oob                         	0x447b
#define	mem_le_preq_auth                        	0x447c
#define	mem_le_preq_max_keysize                 	0x447d
#define	mem_le_preq_init_key_distribution       	0x447e
#define	mem_le_preq_resp_key_distribution       	0x447f
#define	mem_le_pres                             	0x4480
#define	mem_le_pres_iocap                       	0x4481
#define	mem_le_pres_oob                         	0x4482
#define	mem_le_pres_auth                        	0x4483
#define	mem_le_pres_max_keysize                 	0x4484
#define	mem_le_pres_init_key_distribution       	0x4485
#define	mem_le_pres_resp_key_distribution       	0x4486
#define	mem_le_pairing_state                    	0x4487
#define	mem_le_enc_state                        	0x4488
#define	mem_le_pairing_mode                     	0x4489
#define	mem_le_tk                               	0x448a
#define	mem_le_ediv                             	0x448e
#define	mem_le_rand                             	0x4490
#define	mem_le_irk                              	0x4498
#define	mem_le_fixed_passkey_flag               	0x44a8
#define	mem_le_secure_connect_enable            	0x44a9
#define	mem_le_secure_connect_flag              	0x44aa
#define	mem_le_sc_calc                          	0x44ab
#define	mem_le_secure_connect_state             	0x44ac
#define	mem_le_sc_confirm_gkey_flag             	0x44ad
#define	mem_le_sc_local_key_invalid             	0x44ae
#define	mem_le_pairing_handle                   	0x44af
#define	mem_le_search_handle_start              	0x44b1
#define	mem_le_search_handle_end                	0x44b3
#define	mem_le_att_offset                       	0x44b5
#define	mem_le_search_att_type_length           	0x44b5
#define	mem_le_search_att_type                  	0x44b6
#define	mem_le_notify_handle                    	0x44c6
#define	mem_le_search_uuid_length               	0x44c8
#define	mem_le_search_uuid                      	0x44c9
#define	mem_le_handle_data_len                  	0x44d9
#define	mem_le_handle_data                      	0x44da
#define	mem_le_adv_param                        	0x44ea
#define	mem_le_adv_interval_min                 	0x44ea
#define	mem_le_adv_interval_max                 	0x44ec
#define	mem_le_adv_type                         	0x44ee
#define	mem_le_adv_own_addr_type                	0x44ef
#define	mem_le_adv_direct_addr_type             	0x44f0
#define	mem_le_adv_direct_addr                  	0x44f1
#define	mem_le_adv_channel_map                  	0x44f7
#define	mem_le_adv_filter_policy                	0x44f8
#define	mem_le_conn_param                       	0x44f9
#define	mem_le_conn_peer_addr_type              	0x44f9
#define	mem_le_conn_peer_addr                   	0x44fa
#define	mem_le_conn_own_addr_type               	0x4500
#define	mem_le_conn_interval_min                	0x4501
#define	mem_le_conn_interval_max                	0x4503
#define	mem_le_conn_latency                     	0x4505
#define	mem_le_conn_superto                     	0x4507
#define	mem_le_scan_params                      	0x4509
#define	mem_le_scan_type                        	0x4509
#define	mem_le_scan_own_addr_type               	0x450a
#define	mem_le_scan_filter_policy               	0x450b
#define	mem_le_lap                              	0x450c
#define	mem_le_uap                              	0x450f
#define	mem_le_nap                              	0x4510
#define	mem_le_xtype_fifo                       	0x4512
#define	mem_le_transmit_window                  	0x4517
#define	mem_le_connection_updata_param          	0x451b
#define	mem_le_l2cap_size                       	0x452b
#define	mem_le_packet_len_recved                	0x452d
#define	mem_le_tx_buff_used                     	0x452e
#define	mem_le_tx_ptr0                          	0x452f
#define	mem_le_tx_ptr1                          	0x4531
#define	mem_le_tx_ptr2                          	0x4533
#define	mem_le_tx_ptr3                          	0x4535
#define	mem_ui_le_uuid_table                    	0x4537
#define	mem_le_cur_attlist_start_ptr            	0x4539
#define	mem_le_cur_handle_start                 	0x453b
#define	mem_le_cur_handle_end                   	0x453d
#define	mem_le_cur_uuid_lenth                   	0x453f
#define	mem_le_cur_uuid                         	0x4540
#define	mem_notify_handle_pool                  	0x4550
#define	mem_le_curr_att_len                     	0x4554
#define	mem_le_signaling_identifier             	0x4555
#define	mem_le_more_data                        	0x4556
#define	mem_lmp_version                         	0x4557
#define	mem_lmp_subversion                      	0x455a
#define	mem_local_name_length                   	0x455c
#define	mem_local_name                          	0x455d
#define	mem_local_name2                         	0x4560
#define	mem_local_name_end                      	0x45a0
#define	mem_unsniff2sniff_timer                 	0x45a1
#define	mem_switch_flag                         	0x45a2
#define	mem_role_switch_flag                    	0x45a3
#define	mem_eeprom_ota_base_addr                	0x45a4
#define	mem_rfc_xmem_start                      	0x45a6
#define	mem_pn_dlci                             	0x45a6
#define	mem_pn_max_frame_size                   	0x45a7
#define	memFCStemp1                             	0x45a9
#define	memFCStemp2                             	0x45aa
#define	memFCStemp3                             	0x45ab
#define	mem_rfcomm_initiator                    	0x45ac
#define	mem_remote_spp_channel                  	0x45ad
#define	mem_HIUfcs_SPP                          	0x45ae
#define	mem_HIUfcs_SPP_WCredits                 	0x45af
#define	mem_remote_credits                      	0x45b0
#define	mem_credit_given                        	0x45b2
#define	mem_ms_channel                          	0x45b3
#define	mem_current_packet_length               	0x45b4
#define	mem_profile_channel                     	0x45b6
#define	mem_rfc_l2capch_ptr                     	0x45b7
#define	mem_rfc_server_state                    	0x45b9
#define	mem_rfc_xmem_end                        	0x45bb
#define	mem_ui_uuid_table                       	0x45bb
#define	mem_all_uuid_16bits                     	0x45bd
#define	mem_all_uuid_128bits                    	0x45d3
#define	mem_sdp_l2capch_ptr                     	0x45f5
#define	mem_sp_local_key_invalid                	0x45f7
#define	mem_le_private_key_256                  	0x45f8
#define	mem_le_pubkey_local_x_256               	0x4618
#define	mem_le_pubkey_local_y_256               	0x4638
#define	mem_sp_private_key                      	0x4658
#define	mem_sp_pubkey_local                     	0x4670
#define	mem_sp_pubkey_local_x                   	0x4670
#define	mem_sp_pubkey_local_x_end               	0x4688
#define	mem_sp_pubkey_local_y                   	0x4688
#define	mem_ssp_enable                          	0x46a0
#define	mem_sp_iocap_local                      	0x46a1
#define	mem_ssp_mode_flag                       	0x46a4
#define	mem_spp_reject_justwork_flag            	0x46a5
#define	mem_sp_iocap_remote                     	0x46a6
#define	mem_flag_mode_ssp_pin                   	0x46a9
#define	mem_authentication_passkey_times        	0x46aa
#define	mem_passkey_1bit                        	0x46ab
#define	mem_flag_pairing_state                  	0x46ac
#define	mem_ipc_lock_bt                         	0x46ad
#define	mem_ipc_lock_c51                        	0x46ae
#define	mem_ipc_fifo_bt2c51                     	0x46af
#define	mem_ipc_fifo_c512bt                     	0x46b4
#define	mem_led_switch                          	0x46b9
#define	mem_ui_button_timer                     	0x46ba
#define	mem_ui_button_last_state                	0x46bb
#define	mem_ui_timer_last_btclk                 	0x46bc
#define	memui_reconnect_mode                    	0x46c0
#define	mem_ui_state_map                        	0x46c1
#define	mem_ui_profile_supported                	0x46c3
#define	mem_led_gpio                            	0x46c4
#define	mem_led_dark_time                       	0x46c5
#define	mem_led_light_time                      	0x46c7
#define	mem_ui_button_timeout                   	0x46c9
#define	mem_ui_button_gpio                      	0x46ca
#define	mem_pin_length                          	0x46cb
#define	mem_pin                                 	0x46cc
#define	mem_uppersm_xmem_start                  	0x46dc
#define	mem_major_uppersm                       	0x46dc
#define	mem_sub_uppersm                         	0x46dd
#define	mem_uppersm_list                        	0x46de
#define	mem_uppersm_disl2capch_index            	0x46e3
#define	mem_uppersm_xmem_end                    	0x46e4
#define	mem_tws_bdaddr                          	0x46e4
#define	mem_tws_lap                             	0x46e4
#define	mem_tws_uap                             	0x46e7
#define	mem_tws_nap                             	0x46e8
#define	mem_tws_state                           	0x46ea
#define	mem_tws_freq                            	0x46eb
#define	mem_tws_rcv_long_pck                    	0x46ec
#define	mem_tws_pairing_timeout_count           	0x46ed
#define	mem_tws_pairing_timeout                 	0x46ef
#define	mem_wait_connected_timeout_count        	0x46f1
#define	mem_wait_connected_timeout              	0x46f3
#define	mem_loss_match                          	0x46f5
#define	mem_ack_interval                        	0x46f7
#define	mem_ack_interval_count                  	0x46f8
#define	mem_tws_temp                            	0x46f9
#define	mem_tws_rx_type                         	0x46fa
#define	mem_tws_am_addr                         	0x46fb
#define	mem_tws_arq                             	0x46fc
#define	mem_count_master_loss_link              	0x46fd
#define	mem_count_rcv_adv                       	0x46fe
#define	mem_tws_adv_match                       	0x46ff
#define	mem_tws_ack                             	0x4700
#define	mem_tws_loss_ack                        	0x4701
#define	mem_tws_count_poll                      	0x4702
#define	mem_acl_credits                         	0x4704
#define	mem_allow_switch                        	0x4706
#define	mem_hci_acl_queue_start                 	0x4707
#define	mem_hci_wake_clk                        	0x470b
#define	mem_a2dp_uuid                           	0x4704
#define	mem_nv_data                             	0x48f8
#define	mem_nv_data0                            	0x48f8
#define	mem_nv_data1                            	0x4910
#define	mem_nv_data2                            	0x4928
#define	mem_nv_data3                            	0x4940
#define	mem_nv_data4                            	0x4958
#define	mem_gpio3_curr_state                    	0x4970
#define	mem_gpio3_state                         	0x4971
#define	mem_gpio4_curr_state                    	0x4972
#define	mem_gpio4_state                         	0x4973
#define	mem_gpio5_curr_state                    	0x4974
#define	mem_gpio5_state                         	0x4975
#define	mem_le_att_list                         	0x4976
#define	mem_usb_status                          	0x4704
#define	mem_usb_fifo_empty                      	0x4705
#define	mem_usb_read_len                        	0x4706
#define	mem_usb_rxbuf                           	0x4707
#define	mem_usb_state                           	0x4747
#define	mem_bufptr                              	0x4748
#define	mem_remain                              	0x474a
#define	mem_devicedesc                          	0x474b
#define	mem_hidreportdesc_kb                    	0x475f
#define	mem_hidreportdesc_m                     	0x4827
#define	mem_confdesc                            	0x48ef
#define	mem_string0                             	0x4953
#define	mem_string1                             	0x4958
#define	mem_string2                             	0x4976
#define	mem_string3                             	0x4994
#define	mem_usb_setup                           	0x49b2
#define	mem_usb_setup_bmRequestType             	0x49b2
#define	mem_usb_setup_bRequest                  	0x49b3
#define	mem_usb_setup_bValue                    	0x49b4
#define	mem_usb_setup_bValueH                   	0x49b5
#define	mem_usb_setup_wIndex                    	0x49b6
#define	mem_usb_setup_bLength                   	0x49b8
#define	mem_usb_setup_bLengthH                  	0x49b9
#define	mem_usb0_setup                          	0x49ba
#define	mem_usb0_set_report_data                	0x49fa
#define	mem_usb0_get_report_data                	0x4a3a
#define	mem_usb_setup_bValue_temp               	0x4a7a
#define	mem_usb0_get_set_report                 	0x4a7c
#define	mem_usb0_data_ready_report              	0x4a7d
#define	mem_usb_tx_win_enable                   	0x4a7e
#define	mem_usb_tx_mac_enable                   	0x4a7f
#define	mem_usb_zero_packet                     	0x4a80
#define	mem_usb_ones_packet                     	0x4a82
#define	mem_usb_two_packet                      	0x4a84
#define	mem_usb_idle_flag                       	0x4a86
#define	mem_usb_idle_rate                       	0x4a87
#define	mem_usb_get_protocol_flag               	0x4a88
#define	mem_usb_set_protocol_status             	0x4a89
#define	mem_usb_set_protocol_value              	0x4a8a
#define	mem_usb0_state                          	0x4a8b
#define	mem_usb_remote_wakeup                   	0x4a8c
#define	mem_usb_clear_remote_wakeup             	0x4a8d
#define	mem_usb_ep0_stall_status                	0x4a8e
#define	mem_usb_ep1_stall_status                	0x4a8f
#define	mem_usb_ep2_stall_status                	0x4a90
#define	mem_usb_ep3_stall_status                	0x4a91
#define	mem_dsc_info_data_pointer               	0x4a92
#define	mem_dsc_info_len                        	0x4a94
#define	mem_usb_ep1_data                        	0x4a95
#define	mem_usb_ep2_data                        	0x4a96
#define	mem_usb_tx_enable                       	0x4a97
#define	mem_usb_tx_wait                         	0x4a98
#define	mem_usb_device_enumeration_endflag      	0x4a99
#define	mem_usb_wakestate_onetime_flag          	0x4a9a
#define	mem_usb_mac_wakeup_trig                 	0x4a9b
#define	mem_usb_set_high_addr_flag              	0x4a9c
#define	mem_usb_clear_halt                      	0x4a9d
#define	mem_usb_mouse_data                      	0x4a9e
#define	mem_usb_kb_data                         	0x4aae
#define	mem_usb_kb_multikey                     	0x4abe
#define	mem_usb_test_cnt                        	0x4ace
#define	mem_usb_test_kb                         	0x4acf
#define	mem_24g_rxbuf                           	0x4ad0
#define	mem_24g_rxdata                          	0x4af4
#define	mem_24g_rxdata_length                   	0x4b18
#define	mem_24g_rx_crc                          	0x4b19
#define	mem_24g_rx_crc_cal                      	0x4b1b
#define	mem_24g_crc                             	0x4b1d
#define	mem_24g_pid                             	0x4b1f
#define	mem_24g_datalen                         	0x4b20
#define	mem_24g_data_type                       	0x4b21
#define	mem_24g_txdata                          	0x4b22
#define	mem_24g_txlen                           	0x4b42
#define	mem_24g_txpayload                       	0x4b43
#define	mem_24g_rx_window                       	0x4b6e
#define	mem_24g_ensure                          	0x4b70
#define	mem_24g_txfail_cnt                      	0x4b71
#define	mem_24g_get_ack_fail                    	0x4b72
#define	mem_24g_fast_tx                         	0x4b73
#define	mem_24g_fast_hop                        	0x4b74
#define	mem_24g_exit_flag                       	0x4b75
#define	mem_24g_tx_flag                         	0x4b76
#define	mem_24g_retry                           	0x4b77
#define	mem_24g_ch                              	0x4b78
#define	mem_24g_current_ch_number               	0x4b79
#define	mem_24g_ch_map1                         	0x4b7a
#define	mem_24g_ch_map2                         	0x4b7e
#define	mem_24g_ch_map3                         	0x4b82
#define	mem_24g_ch_map4                         	0x4b86
#define	mem_24g_tx_btclk                        	0x4b8a
#define	mem_24g_interval                        	0x4b8e
#define	mem_24g_interval_min                    	0x4b8f
#define	mem_24g_interval_max                    	0x4b90
#define	mem_24g_addr_length                     	0x4b91
#define	mem_24g_addr                            	0x4b92
#define	mem_24g_paring_addr                     	0x4b98
#define	mem_24g_pairing_flag                    	0x4b9e
#define	mem_24g_pairing_timer_flag              	0x4b9f
#define	mem_24g_pairing_sm                      	0x4ba0
#define	mem_24g_enter_lpm_timer                 	0x4ba1
#define	mem_24g_enter_hibernate_flag            	0x4ba2
#define	mem_24g_enter_hibernate                 	0x4ba3
#define	mem_24g_abort_flag                      	0x4bab
#define	mem_24g_data_pid                        	0x4bac
#define	mem_24g_common_temp                     	0x4bad
#define	mem_24g_payload_rxbuf                   	0x4bcd
#define	mem_24g_pac_len                         	0x4bed
#define	mem_queue_ele_num                       	0x4bee
#define	mem_queue_read                          	0x4bef
#define	mem_queue_write                         	0x4bf1
#define	mem_queue_start                         	0x4bf3
#define	mem_data_ele0                           	0x4bf3
#define	mem_data_ele1                           	0x4c13
#define	mem_data_ele2                           	0x4c33
#define	mem_queue_end                           	0x4c53
#define	mem_queue_temp                          	0x4c53
#define	mem_24g_check_dongle_times              	0x4c55
#define	mem_24g_rxdata_temp                     	0x4c57
#define	mem_24g_dongle_private_addr             	0x4c7b
#define	mem_dongle_mode_init                    	0x4c81
#define	mem_dongle_work_mode                    	0x4c82
#define	mem_dongle_ms_bind_step                 	0x4c83
#define	mem_dongle_kb_bind_step                 	0x4c84
#define	mem_dongle_bind_device_status           	0x4c85
#define	mem_24g_bind_rf_data                    	0x4c86
#define	mem_24g_bind_payload                    	0x4c96
#define	mem_24g_abort_packet                    	0x4c9d
#define	mem_24g_rf_laststa                      	0x4c9e
#define	mem_24g_rf_receive                      	0x4c9f
#define	mem_24g_rx_interrupt                    	0x4ca0
#define	mem_dongle_tx_btclk                     	0x4ca1
#define	mem_dongle_interval                     	0x4ca5
#define	mem_rssi_noise_buf                      	0x4ca6
#define	mem_rssi_signal_buf                     	0x4cc6
#define	mem_rssi_noise_avg                      	0x4ce6
#define	mem_rssi_signal_avg                     	0x4ce7
#define	mem_rssi_snr_opposite                   	0x4ce8
#define	mem_rssi_noise_buf_index                	0x4ce9
#define	mem_rssi_signal_buf_index               	0x4cea
#define	mem_24g_get_user_defined_flag           	0x4ceb
#define	mem_24g_get_user_defined_data           	0x4cec
#define	mem_last_txlch                          	0x4704
#define	mem_last_txlen                          	0x4705
#define	mem_last_txdata                         	0x4707
#define	mem_nv_le_data                          	0x471b
#define	mem_nv_le_data0                         	0x471b
#define	mem_nv_le_data1                         	0x4733
#define	mem_nv_le_data2                         	0x474b
#define	mem_nv_le_data3                         	0x4763
#define	mem_nv_le_data4                         	0x477b
#define	mem_le_att_rf                           	0x4793
#define	mem_rc_att_list                         	0x47b1
#define	mem_aes_input_len                       	0x4cc5
#define	mem_aes_key                             	0x4cc6
#define	mem_aes_input                           	0x4cd6
#define	mem_aes_output                          	0x4ce6
#define	mem_write_req_data_len                  	0x4cf6
#define	mem_write_req_data                      	0x4cf7
#define	mem_random_len                          	0x4d0b
#define	mem_random_buff                         	0x4d0c
#define	mem_ipc_le_data_notify_len              	0x4d8c
#define	mem_ipc_le_data_offset                  	0x4d8d
#define	mem_ipc_le_data_not_finish_send         	0x4d8e
#define	mem_ipc_le_data_continue_inuse          	0x4d8f
#define	mem_ipc_le_data_temp_rptr               	0x4d90
#define	mem_ipc_le_data_att_handle_expect1      	0x4d92
#define	mem_ipc_le_data_att_handle_expect2      	0x4d94
#define	mem_ipc_le_data_prepare_write_req_offset	0x4d96
#define	mem_ipc_le_data_prepare_write_len       	0x4d98
#define	mem_att_send_handle                     	0x4d99
#define	mem_ipc_adv_data_len                    	0x4d9b
#define	mem_ipc_adv_data                        	0x4d9c
#define	mem_ipc_scan_rsp_data_len               	0x4dec
#define	mem_ipc_scan_rsp_data                   	0x4ded
#define	mem_att_long_uuid_temp                  	0x4e3d
#define	mem_long_uuid                           	0x4e4d
#define	mem_read_req_data                       	0x4e7d
#define	mem_flash_start_addr                    	0x4e81
#define	mem_mcmd                                	0xff0
#define	mem_mouse_data                          	0xff1
#define	mem_l2cap_rxbuff1                       	0x1000
#define	mem_l2cap_rxbuff2                       	0x1400
#define	mem_tx_buff0                            	0x1800
#define	mem_tx_buff1                            	0x1880
#define	mem_tx_buff2                            	0x1900
#define	mem_tx_buff3                            	0x1980
#define	mem_tx_buff4                            	0x1a00
#define	mem_tx_buff5                            	0x1a80
#define	mem_tx_buff6                            	0x1b00
#define	mem_tx_buff7                            	0x1b80
#define	mem_le_tx_buffer0                       	0x1c00
#define	mem_le_tx_buffer1                       	0x1c80
#define	mem_le_tx_buffer2                       	0x1d00
#define	mem_le_tx_buffer3                       	0x1d80
#define	mem_h5rx_buf                            	0x1e00
#define	mem_h5rx_buf_end                        	0x1eff
#define	mem_h5tx_buf                            	0x1f00
#define	mem_h5tx_buf_end                        	0x1fff
#define	mmem_qspi_tbuf                          	0x10000
#define	IPC_MEM_BLOCK_START                     	0x10000
#define	IPC_TO_BT_BUF_START_ADDR                	0x10000
#define	IPC_TO_BT_BUF_END_ADDR                  	0x10300
#define	IPC_TO_BT_WPTR_ADDR                     	0x10300
#define	IPC_TO_BT_RPTR_ADDR                     	0x10304
#define	IPC_TO_M0_WPTR_ADDR                     	0x10308
#define	IPC_TO_M0_RPTR_ADDR                     	0x1030c
#define	IPC_TO_M0_BUF_START_ADDR                	0x10350
#define	IPC_TO_M0_BUF_END_ADDR                  	0x10500
#define	IPC_MEM_ELOCK_END                       	0x10500
#define	IPC_TYPE_CMD                            	0x01
#define	IPC_TYPE_EVT                            	0x02
#define	IPC_TYPE_HID                            	0x03
#define	IPC_TYPE_SPP                            	0x04
#define	IPC_TYPE_BLE                            	0x05
#define	IPC_TYPE_24G                            	0x06
#define	IPC_TYPE_MESH                           	0x07
#define	IPC_TYPE_ADV                            	0x08
#define	IPC_TYPE_SCAN                           	0x09
#define	IPC_TYPE_A2DP                           	0x0a
#define	IPC_TYPE_HFP                            	0x0b
#define	IPC_READ_REQ                            	0x0c
#endif
