#ifndef __FLASH_CONFIG_H__
#define __FLASH_CONFIG_H__
#define FLASH_TYPE_P25D 0
#define FLASH_TYPE_W25Q16 1

#define FLASH_WRTIE_FLAG		(0x55AAAA55)

#define FLASH_ID FLASH_TYPE_P25D

#if (FLASH_ID == FLASH_TYPE_P25D)
#define PAGE_SIZE 				(256)//0x1000
#else
#define PAGE_SIZE 				(4*1024)//0x1000
#endif
#define PAGE_MASK 				(~(PAGE_SIZE-1))
#define BUFF_SIZE 				(256)

#define FLASH_START_ADDR		0x00000000
#if (FLASH_ID == FLASH_TYPE_P25D)
#define FLASH_SIZE 				0x00080000	/*512K Byte*/
#else
#define FLASH_SIZE 				0x00200000	/*2M Byte*/
#endif

#define CODE_START_ADDR			0x00000000
#define CODE_SIZE				0x0003E000	/*248K Byte*/

#define CODE_UPGRADE_START_ADDR	0x0003E000
#define CODE_UPGRADE_SIZE		0x0003E000	/*248K Byte*/

#define CONFIG_START_ADDR		0x0007D000	/*4K  Byte*/
#define CONFIG_SIZE				0x1000	

#define CONFIG_ECDH_KEY_ADDR	(CONFIG_START_ADDR+PAGE_SIZE)	/*256  Byte*/
#define CONFIG_ECDH_KEY_SIZE	(32+32+32+4)	/*96+4 Byte*/
#define CONFIG_ECDH_PKX_ADDR	(CONFIG_ECDH_KEY_ADDR)
#define CONFIG_ECDH_PKY_ADDR	(CONFIG_ECDH_PKX_ADDR+32)
#define CONFIG_ECDH_PRI_ADDR	(CONFIG_ECDH_PKY_ADDR+32)

#define SECTION_START_ADDR		0x0007E000	/*PAGE_SIZE*6 Byte*/
#define SECTION_SIZE			PAGE_SIZE
#define SECTION_NUM				6
#define SECTION_ADDR(num) 		(num<6?(SECTION_START_ADDR+num*SECTION_SIZE)\
									:FLASH_START_ADDR+FLASH_SIZE)

#if (FLASH_ID == FLASH_TYPE_P25D)
#define APP_START_ADDR			(SECTION_START_ADDR+SECTION_SIZE*SECTION_NUM)
#define APP_SIZE				(FLASH_START_ADDR+FLASH_SIZE-APP_START_ADDR)	/*remain byte*/

#else
#define SWAP_ADDR 				(SECTION_START_ADDR+SECTION_SIZE*SECTION_NUM)
#define SWAP_SIZE				PAGE_SIZE	

#define APP_START_ADDR			(SWAP_ADDR+SWAP_SIZE)
#define APP_SIZE				(FLASH_START_ADDR+FLASH_SIZE-APP_START_ADDR)	/*remain byte*/

#endif

#endif/*__FLASH_CONFIG_H__*/
